### PR TITLE
fix for issue 68

### PR DESCRIPTION
**Pull request by LegacyID1991**
Related to #68 

removed userName folder from work folder structure in accord with issue 68

- This will not however move all of the present work files from old location, they still need to be manually copyd or moved to the new folder when the new tasks are created.

From now on all artists will work in the same app work dir under the tasks for each asset or shot.

### CODE REVIEW

**Comment by mottosso** [comment]
Tested and works well?

**Comment by LegacyID1991** [comment]
Only tested at home PC not in Facility, but yea no issues.
could do a pull to mb-dev for @CalleHalldin to try it out.

**Comment by mottosso** [comment]
Looks good but yeah, better test first.

**Comment by LegacyID1991** [comment]
This Branch is now active on mb-dev.bat

Go nuts @CalleHalldin

**Comment by mottosso** [comment]
Should this be merged?

**Comment by LegacyID1991** [comment]
Me and @CalleHalldin talked it over and we said that it works fine.
But we will wait to merge this till we have completed our current projects, otherwise all of the artists work will need to be copyd to the new folders and this will cause maya starts to missbehave like #97

**Comment by mottosso** [comment]
It really shouldnt cause any issues to have changed where work folders are located, the issue of 97 seems to be that someone has moved assets around after having referenced then into a scene.

You should be able to save your files anywhere, even on the desktop and references should still work. Calle can confirm this.

The goal of every single update to this pipeline should always work with existing and future projects in parallel. If this isn't true then we have messed up somewhere.

**Comment by mottosso** [comment]
Deprecating the old mb.bat

**Pull request closed without merging**
