### PR TITLE
Launcher GUI

### PR DESCRIPTION
**Pull request by mottosso**
First pass at Launcher, will continue to update this thread as development progresses.

For feedback on fundamental layout and function, now is the time.

untitled project

To be written..

1. Style, such as colors, icons and size of things
2. Better inspection of running processes, including killing them
3. Environment management, currently this does not add anything to the environment; the format is something we will need to discuss. Initially, I'm thinking I'll use the `.bat` files as-is for things such as start/end frame etc. But before we're through we should consider a more appropriate and extensible format, such as `ini`.

See #61 for details.

### CODE REVIEW

**Comment by tws0002** [comment]
can i test this ?

**Comment by mottosso** [comment]
You can run it, but it currently doesn't do much other than launch Maya. It doesn't launch it into the pipeline, like `mb.bat` is.

Currently we are evaluating appearance only.

Wait till tomorrow, and you'll be able to test it out better.

**Comment by CalleHalldin** [comment]
Hey looks great! I will show it to the rest of the office tomorrow. Would it be possible to define and create "users" instead of the pipeline looking at the computer network name (or whatever it looks at)? Also to be able to create projects, assets, shots from this GUI. Not sure how far you are planning to take this. The current state looks great though!

**Comment by mottosso** [comment]
> Would it be possible to define and create "users" instead of the pipeline looking at the computer network name (or whatever it looks at)?

Sure, that's possible. Let's explore the ideal solution first; that is, could you create your user via your OS? As a regular Windows user.

> Also to be able to create projects, assets, shots from this GUI. 

Sure, that's a good idea.

**Comment by BigRoy** [comment]
Two minor tips:

- I'd recommend avoiding the need for the _load_ button and instead just allow double clicking the name of the app on the right hand side. (Use it like a regular "browser")
- To give instant feedback to the Artist it works very well to add a statusbar that displays brief messages from the monitor (the log) at the bottom of the UI. Then starting the application instantly results in a "Launching: x" message.

> You can run it, but it currently doesn't do much other than launch Maya. It doesn't launch it into the pipeline, like mb.bat is.

Our launcher is launching the `.bat` files to start within the pipeline. I'm assuming this would be done here as well?

**Comment by mottosso** [comment]
> Our launcher is launching the .bat files to start within the pipeline. I'm assuming this would be done here as well?

I'm still working on the most straightforward solution to this.

Currently, you register names of executables with the launcher, such as `maya2016`. It then expects to find this on your `PATH`. The problem is that they also need to set the appropriate `userSetup` path for Maya, and do it differently from Nuke. So there's configuration to be made in both the launcher and the `.bat` files.

I experimented with having all of it in a single configuration, but it got complicated fast.

How are your .bat files looking?

**Comment by mottosso** [comment]
To your suggestions, I like it. Will do that, thanks!

**Comment by BigRoy** [comment]
> How are your .bat files looking?

In our case the launcher has a set of "root paths" that can be registered that have a suite of `.bat` files alongside `.png` icons, these are the tools that are then listed in the launcher. We have the `launcher` roots one folder down from the pipeline `bin` (pipeline .bat files): `bin/launchers/maya2016.bat`. This would then call `setup_environment.bat` from the folder above, etc. Does that make sense?

E.g. the launcher for `maya2017.bat` would look like:

```batch
@echo OFF
pushd %~dp0..\..

call set_environment.bat
call python_environment.bat
call maya2017_environment.bat
call maya2017.bat %*
```

**Comment by mottosso** [comment]
> Does that make sense?

Perfect sense, I would have done it the same way.

Continuing the project in a separate repository here: 

- https://github.com/mindbender-studio/launcher/pull/1

**Pull request closed without merging**
